name: proyecto_tesis
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.17.4
  grouped_buttons: ^1.0.4
  intl: ^0.17.0
  http:
  provider:
  flutter_spinkit:
  flutter_bloc: ^7.0.0
  rxdart: ^0.27.3
  image_picker: ^0.8.4
  shared_preferences: ^2.0.8
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.1.0

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/



